version: "3"
services:
    
    chal_1:
        image: "php:apache"
        build: "chal_1"
        ports:
            - "2050:80"
        volumes:
            - ./chal_1/www:/var/www/html

    chal_2:
        image: "php:apache"
        build: "chal_2"
        ports:
            - "2048:80"
        volumes:
            - ./chal_2/www:/var/www/html
